name: Analysis

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  should_run:
    name: Check preconditions
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      continue: ${{ steps.changed.outputs.src_changed_count > 0 }}
    steps:
      - name: Log event trigger
        run: cat $GITHUB_EVENT_PATH
      - name: Download build metadata
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{github.event.workflow.id}}
          run_id: ${{github.event.workflow_run.id}}
          name: metadata
      - id: changed
        name: Check changed files
        run: |
          changed_count=$(jq -r '.changedPaths[]' metadata.json | grep '^src/' | grep '.js$' | wc -l)
          echo "::set-output name=src_changed_count::$changed_count"

  initialize:
    name: Initialize analysis environment
    runs-on: ubuntu-latest
    needs: should_run
    # if: needs.should_run.outputs.continue == 'true'
    steps:
      - name: Debug inputs
        run: echo ${{needs.should_run.outputs.continue}}
      # Determine BASE_REF & BASE_SHA
      - name: Download build metadata
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{github.event.workflow.id}}
          run_id: ${{github.event.workflow_run.id}}
          name: metadata
      - name: Set metadata env variables
        run: |
          cat metadata.json
          echo "BASE_REF=$(jq --raw-output '.base.ref' metadata.json)" >> $GITHUB_ENV
          echo "BASE_SHA=$(jq --raw-output '.base.sha' metadata.json)" >> $GITHUB_ENV
      # Consolidate workflow package and base package into a single artifact for benchmark jobs
      - name: Download build output package
        uses: dawidd6/action-download-artifact@v2
        with:
          name: npm-package
          workflow: ${{github.event.workflow.id}}
          run_id: ${{github.event.workflow_run.id}}
          path: build-output
      - name: Prepare build output
        run: |
          cd build-output
          tar -xzf preact.tgz
      - name: Upload build output locally
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: build-output/package/
      - name: Download base build package
        uses: andrewiggins/download-base-artifact@v1
        with:
          artifact: npm-package
          path: base
          workflow: ${{github.event.workflow.id}}
          baseRef: ${{env.BASE_REF}}
          baseSha: ${{env.BASE_SHA}}
      - name: Upload base build package locally
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: base/preact.tgz
      - name: Debug env
        run: |
          echo $BASE_REF
          echo $BASE_SHA
      # Initialize tachometer comment
      - name: Initialize Tachometer Results Report
        uses: andrewiggins/tachometer-reporter-action@v2
        with:
          initialize: true

  bench_text_update:
    name: Bench text_update
    runs-on: ubuntu-latest
    needs: initialize
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/download-artifact@v2
        with:
          name: build-output
      - name: install & build
        run: |
          cd benches
          npm ci
      - name: bench
        run: |
          export CHROMEDRIVER_FILEPATH=$(which chromedriver)
          cd benches
          npm run bench text_update.html
      - uses: andrewiggins/tachometer-reporter-action@v2
        with:
          path: benches/results/text_update.json
          report-id: text_update
          base-bench-name: preact-master
          pr-bench-name: preact-local
  # bench_many_updates:
  #   name: Bench many_updates
  #   runs-on: ubuntu-latest
  #   needs: initialize
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: build-output
  #     - name: install & build
  #       run: |
  #         cd benches
  #         npm ci
  #     - name: bench
  #       run: |
  #         export CHROMEDRIVER_FILEPATH=$(which chromedriver)
  #         cd benches
  #         npm run bench many_updates.html
  #     - uses: andrewiggins/tachometer-reporter-action@v2
  #       with:
  #         path: benches/results/many_updates.json
  #         report-id: many_updates
  #         base-bench-name: preact-master
  #         pr-bench-name: preact-local
  # bench_02_replace1k:
  #   name: Bench 02_replace1k
  #   runs-on: ubuntu-latest
  #   needs: initialize
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: build-output
  #     - name: install & build
  #       run: |
  #         cd benches
  #         npm ci
  #     - name: bench
  #       run: |
  #         export CHROMEDRIVER_FILEPATH=$(which chromedriver)
  #         cd benches
  #         npm run bench 02_replace1k.html
  #     - uses: andrewiggins/tachometer-reporter-action@v2
  #       with:
  #         path: benches/results/02_replace1k.json
  #         report-id: 02_replace1k
  #         base-bench-name: preact-master
  #         pr-bench-name: preact-local
  #         summarize: 'duration, usedJSHeapSize'
  # bench_03_update10th1k_x16:
  #   name: Bench 03_update10th1k_x16
  #   runs-on: ubuntu-latest
  #   needs: initialize
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: build-output
  #     - name: install & build
  #       run: |
  #         cd benches
  #         npm ci
  #     - name: bench
  #       run: |
  #         export CHROMEDRIVER_FILEPATH=$(which chromedriver)
  #         cd benches
  #         npm run bench 03_update10th1k_x16.html
  #     - uses: andrewiggins/tachometer-reporter-action@v2
  #       with:
  #         path: benches/results/03_update10th1k_x16.json
  #         report-id: 03_update10th1k_x16
  #         base-bench-name: preact-master
  #         pr-bench-name: preact-local
  # bench_07_create10k:
  #   name: Bench 07_create10k
  #   runs-on: ubuntu-latest
  #   needs: initialize
  #   timeout-minutes: 20
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: build-output
  #     - name: install & build
  #       run: |
  #         cd benches
  #         npm ci
  #     - name: bench
  #       run: |
  #         export CHROMEDRIVER_FILEPATH=$(which chromedriver)
  #         cd benches
  #         npm run bench 07_create10k.html
  #     - uses: andrewiggins/tachometer-reporter-action@v2
  #       with:
  #         path: benches/results/07_create10k.json
  #         report-id: 07_create10k
  #         base-bench-name: preact-master
  #         pr-bench-name: preact-local
  # bench_hydrate1k:
  #   name: Bench hydrate1k
  #   runs-on: ubuntu-latest
  #   needs: initialize
  #   timeout-minutes: 20
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: build-output
  #     - name: install & build
  #       run: |
  #         cd benches
  #         npm ci
  #     - name: bench
  #       run: |
  #         export CHROMEDRIVER_FILEPATH=$(which chromedriver)
  #         cd benches
  #         npm run bench hydrate1k.html
  #     - uses: andrewiggins/tachometer-reporter-action@v2
  #       with:
  #         path: benches/results/hydrate1k.json
  #         report-id: hydrate1k
  #         base-bench-name: preact-master
  #         pr-bench-name: preact-local
  # bench_filter_list:
  #   name: Bench filter_list
  #   runs-on: ubuntu-latest
  #   needs: initialize
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: build-output
  #     - name: install & build
  #       run: |
  #         cd benches
  #         npm ci
  #     - name: bench
  #       run: |
  #         export CHROMEDRIVER_FILEPATH=$(which chromedriver)
  #         cd benches
  #         npm run bench filter_list.html
  #     - uses: andrewiggins/tachometer-reporter-action@v2
  #       with:
  #         path: benches/results/filter_list.json
  #         report-id: filter_list
  #         base-bench-name: preact-master
  #         pr-bench-name: preact-local
